### ISSUE TITLE
Default port collision

### ISSUE THREAD

**Issue by jvmlet** [clintonmagro/embedded-qpid-spring-boot-starter#1]
Hello
First of all - well done , thanks a lot for putting this together and congrats with first issue :
Would you please change the default `qpid`  port to **not** collision with default rabbit mq port ?
The  common situation is that Rabbit MQ broker **IS** running on default port on dev machines, setting up the test requires me to have this :

````
embedded:
  qpid:
    port: 5656
spring:
  rabbitmq:
    port: 5656
```` 

Would be great if  these 2 properties be set implicitely still allowing to have rabbit mq broker running on default `5672`
Thanks a lot again.
